version: '3.8'

services:
  app:
    build: .
    container_name: wp-automation
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./images:/app/images
      - ./app.log:/app/app.log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 